### ISSUE TITLE
bug in PayRequestAttributes

### ISSUE THREAD

**Issue by tsitsishvili** [payzeio/laravel-payze#8]
payzeio/laravel-payze/src/Concerns/PayRequestAttributes.php

message : Undefined array key "succes"

maybe key must be "success", not "succes"

![Screenshot 2022-10-05 at 21 51 02](https://user-images.githubusercontent.com/80920564/194128477-e58bfb42-13f6-4282-95e4-a2aba8982057.png)

**Comment by Lotuashvili** [comment]
This has been fixed in https://github.com/payzeio/laravel-payze/commit/930980b6b06ee289e13d6d20970fb59d61cafa91

Sorry for an inconvenience.
